module.exports = [
    { "id": 1, "country_name": "Afganistán", "code": "93" },
    { "id": 2, "country_name": "Albania", "code": "355" },
    { "id": 3, "country_name": "Alemania", "code": "49" },
    { "id": 4, "country_name": "Algeria", "code": "213" },
    { "id": 5, "country_name": "Andorra", "code": "376" },
    { "id": 6, "country_name": "Angola", "code": "244" },
    { "id": 7, "country_name": "Anguila", "code": "1 264" },
    { "id": 8, "country_name": "Antártida", "code": "672" },
    { "id": 9, "country_name": "Antigua y Barbuda", "code": "1 268" },
    { "id": 10, "country_name": "Antillas Neerlandesas", "code": "599" },
    { "id": 11, "country_name": "Arabia Saudita", "code": "966" },
    { "id": 12, "country_name": "Argentina", "code": "54" },
    { "id": 13, "country_name": "Armenia", "code": "374" },
    { "id": 14, "country_name": "Aruba", "code": "297" },
    { "id": 15, "country_name": "Australia", "code": "61" },
    { "id": 16, "country_name": "Austria", "code": "43" },
    { "id": 17, "country_name": "Azerbayán", "code": "994" },
    { "id": 18, "country_name": "Bahamas", "code": "1 242" },
    { "id": 19, "country_name": "Bahrein", "code": "973" },
    { "id": 20, "country_name": "Bangladesh", "code": "880" },
    { "id": 21, "country_name": "Barbados", "code": "1 246" },
    { "id": 22, "country_name": "Bélgica", "code": "32" },
    { "id": 23, "country_name": "Belice", "code": "501" },
    { "id": 24, "country_name": "Benín", "code": "229" },
    { "id": 25, "country_name": "Bhután", "code": "975" },
    { "id": 26, "country_name": "Bielorrusia", "code": "375" },
    { "id": 27, "country_name": "Birmania", "code": "95" },
    { "id": 28, "country_name": "Bolivia", "code": "591" },
    { "id": 29, "country_name": "Bosnia y Herzegovina", "code": "387" },
    { "id": 30, "country_name": "Botsuana", "code": "267" },
    { "id": 31, "country_name": "Brasil", "code": "55" },
    { "id": 32, "country_name": "Brunéi", "code": "673" },
    { "id": 33, "country_name": "Bulgaria", "code": "359" },
    { "id": 34, "country_name": "Burkina Faso", "code": "226" },
    { "id": 35, "country_name": "Burundi", "code": "257" },
    { "id": 36, "country_name": "Cabo Verde", "code": "238" },
    { "id": 37, "country_name": "Camboya", "code": "855" },
    { "id": 38, "country_name": "Camerún", "code": "237" },
    { "id": 39, "country_name": "Canadá", "code": "1" },
    { "id": 40, "country_name": "Chad", "code": "235" },
    { "id": 41, "country_name": "Chile", "code": "56" },
    { "id": 42, "country_name": "China", "code": "86" },
    { "id": 43, "country_name": "Chipre", "code": "357" },
    { "id": 44, "country_name": "Ciudad del Vaticano", "code": "39" },
    { "id": 45, "country_name": "Colombia", "code": "57" },
    { "id": 46, "country_name": "Comoras", "code": "269" },
    { "id": 47, "country_name": "Congo", "code": "242" },
    { "id": 48, "country_name": "Congo", "code": "243" },
    { "id": 49, "country_name": "Corea del Norte", "code": "850" },
    { "id": 50, "country_name": "Corea del Sur", "code": "82" },
    { "id": 51, "country_name": "Costa de Marfil", "code": "225" },
    { "id": 52, "country_name": "Costa Rica", "code": "506" },
    { "id": 53, "country_name": "Croacia", "code": "385" },
    { "id": 54, "country_name": "Cuba", "code": "53" },
    { "id": 55, "country_name": "Dinamarca", "code": "45" },
    { "id": 56, "country_name": "Dominica", "code": "1 767" },
    { "id": 57, "country_name": "Ecuador", "code": "593" },
    { "id": 58, "country_name": "Egipto", "code": "20" },
    { "id": 59, "country_name": "El Salvador", "code": "503" },
    { "id": 60, "country_name": "Emiratos Árabes Unidos", "code": "971" },
    { "id": 61, "country_name": "Eritrea", "code": "291" },
    { "id": 62, "country_name": "Escocia", "code": "44" },
    { "id": 63, "country_name": "Eslovaquia", "code": "421" },
    { "id": 64, "country_name": "Eslovenia", "code": "386" },
    { "id": 65, "country_name": "España", "code": "34" },
    { "id": 66, "country_name": "Estados Unidos de América", "code": "1" },
    { "id": 67, "country_name": "Estonia", "code": "372" },
    { "id": 68, "country_name": "Etiopía", "code": "251" },
    { "id": 69, "country_name": "Filipinas", "code": "63" },
    { "id": 70, "country_name": "Finlandia", "code": "358" },
    { "id": 71, "country_name": "Fiyi", "code": "679" },
    { "id": 72, "country_name": "Francia", "code": "33" },
    { "id": 73, "country_name": "Gabón", "code": "241" },
    { "id": 74, "country_name": "Gales", "code": "44" },
    { "id": 75, "country_name": "Gambia", "code": "220" },
    { "id": 76, "country_name": "Georgia", "code": "995" },
    { "id": 77, "country_name": "Ghana", "code": "233" },
    { "id": 78, "country_name": "Gibraltar", "code": "350" },
    { "id": 79, "country_name": "Granada", "code": "1 473" },
    { "id": 80, "country_name": "Grecia", "code": "30" },
    { "id": 81, "country_name": "Groenlandia", "code": "299" },
    { "id": 83, "country_name": "Guam", "code": "1 671" },
    { "id": 84, "country_name": "Guatemala", "code": "502" },
    { "id": 87, "country_name": "Guinea", "code": "224" },
    { "id": 88, "country_name": "Guinea Ecuatorial", "code": "240" },
    { "id": 89, "country_name": "Guinea-Bissau", "code": "245" },
    { "id": 90, "country_name": "Guyana", "code": "592" },
    { "id": 91, "country_name": "Haití", "code": "509" },
    { "id": 92, "country_name": "Honduras", "code": "504" },
    { "id": 93, "country_name": "Hong kong", "code": "852" },
    { "id": 94, "country_name": "Hungría", "code": "36" },
    { "id": 95, "country_name": "India", "code": "91" },
    { "id": 96, "country_name": "Indonesia", "code": "62" },
    { "id": 97, "country_name": "Inglaterra", "code": "44" },
    { "id": 98, "country_name": "Irak", "code": "964" },
    { "id": 99, "country_name": "Irán", "code": "98" },
    { "id": 100, "country_name": "Irlanda", "code": "353" },
    { "id": 101, "country_name": "Irlanda del Norte", "code": "44" },
    { "id": 103, "country_name": "Isla de Man", "code": "44" },
    { "id": 104, "country_name": "Isla de Navidad", "code": "61" },
    { "id": 106, "country_name": "Islandia", "code": "354" },
    { "id": 107, "country_name": "Islas Bermudas", "code": "1 441" },
    { "id": 108, "country_name": "Islas Caimán", "code": "1 345" },
    { "id": 109, "country_name": "Islas Cocos (Keeling)", "code": "61" },
    { "id": 110, "country_name": "Islas Cook", "code": "682" },
    { "id": 112, "country_name": "Islas Feroe", "code": "298" },
    { "id": 115, "country_name": "Islas Maldivas", "code": "960" },
    { "id": 116, "country_name": "Islas Malvinas", "code": "500" },
    { "id": 117, "country_name": "Islas Marianas del Norte", "code": "1 670" },
    { "id": 118, "country_name": "Islas Marshall", "code": "692" },
    { "id": 119, "country_name": "Islas Pitcairn", "code": "870" },
    { "id": 120, "country_name": "Islas Salomón", "code": "677" },
    { "id": 121, "country_name": "Islas Turcas y Caicos", "code": "1 649" },
    { "id": 123, "country_name": "Islas Vírgenes Británicas", "code": "1 284" },
    { "id": 124, "country_name": "Islas Vírgenes de los Estados Unidos", "code": "1 340" },
    { "id": 125, "country_name": "Israel", "code": "972" },
    { "id": 126, "country_name": "Italia", "code": "39" },
    { "id": 127, "country_name": "Jamaica", "code": "1 876" },
    { "id": 128, "country_name": "Japón", "code": "81" },
    { "id": 130, "country_name": "Jordania", "code": "962" },
    { "id": 131, "country_name": "Kazajistán", "code": "7" },
    { "id": 132, "country_name": "Kenia", "code": "254" },
    { "id": 133, "country_name": "Kirgizstán", "code": "996" },
    { "id": 134, "country_name": "Kiribati", "code": "686" },
    { "id": 135, "country_name": "Kuwait", "code": "965" },
    { "id": 136, "country_name": "Laos", "code": "856" },
    { "id": 137, "country_name": "Lesoto", "code": "266" },
    { "id": 138, "country_name": "Letonia", "code": "371" },
    { "id": 139, "country_name": "Líbano", "code": "961" },
    { "id": 140, "country_name": "Liberia", "code": "231" },
    { "id": 141, "country_name": "Libia", "code": "218" },
    { "id": 142, "country_name": "Liechtenstein", "code": "423" },
    { "id": 143, "country_name": "Lituania", "code": "370" },
    { "id": 144, "country_name": "Luxemburgo", "code": "352" },
    { "id": 145, "country_name": "Macao", "code": "853" },
    { "id": 146, "country_name": "Macedônia", "code": "389" },
    { "id": 147, "country_name": "Madagascar", "code": "261" },
    { "id": 148, "country_name": "Malasia", "code": "60" },
    { "id": 149, "country_name": "Malawi", "code": "265" },
    { "id": 150, "country_name": "Mali", "code": "223" },
    { "id": 151, "country_name": "Malta", "code": "356" },
    { "id": 152, "country_name": "Marruecos", "code": "212" },
    { "id": 154, "country_name": "Mauricio", "code": "230" },
    { "id": 155, "country_name": "Mauritania", "code": "222" },
    { "id": 156, "country_name": "Mayotte", "code": "262" },
    { "id": 157, "country_name": "México", "code": "52" },
    { "id": 158, "country_name": "Micronesia", "code": "691" },
    { "id": 159, "country_name": "Moldavia", "code": "373" },
    { "id": 160, "country_name": "Mónaco", "code": "377" },
    { "id": 161, "country_name": "Mongolia", "code": "976" },
    { "id": 162, "country_name": "Montenegro", "code": "382" },
    { "id": 163, "country_name": "Montserrat", "code": "1 664" },
    { "id": 164, "country_name": "Mozambique", "code": "258" },
    { "id": 165, "country_name": "Namibia", "code": "264" },
    { "id": 166, "country_name": "Nauru", "code": "674" },
    { "id": 167, "country_name": "Nepal", "code": "977" },
    { "id": 168, "country_name": "Nicaragua", "code": "505" },
    { "id": 169, "country_name": "Niger", "code": "227" },
    { "id": 170, "country_name": "Nigeria", "code": "234" },
    { "id": 171, "country_name": "Niue", "code": "683" },
    { "id": 172, "country_name": "Noruega", "code": "47" },
    { "id": 173, "country_name": "Nueva Caledonia", "code": "687" },
    { "id": 174, "country_name": "Nueva Zelanda", "code": "64" },
    { "id": 175, "country_name": "Omán", "code": "968" },
    { "id": 176, "country_name": "Países Bajos", "code": "31" },
    { "id": 177, "country_name": "Pakistán", "code": "92" },
    { "id": 178, "country_name": "Palau", "code": "680" },
    { "id": 180, "country_name": "Panamá", "code": "507" },
    { "id": 181, "country_name": "Papúa Nueva Guinea", "code": "675" },
    { "id": 182, "country_name": "Paraguay", "code": "595" },
    { "id": 183, "country_name": "Perú", "code": "51" },
    { "id": 184, "country_name": "Polinesia Francesa", "code": "689" },
    { "id": 185, "country_name": "Polonia", "code": "48" },
    { "id": 186, "country_name": "Portugal", "code": "351" },
    { "id": 187, "country_name": "Puerto Rico", "code": "1" },
    { "id": 188, "country_name": "Qatar", "code": "974" },
    { "id": 189, "country_name": "Reino Unido", "code": "44" },
    { "id": 190, "country_name": "República Centroafricana", "code": "236" },
    { "id": 191, "country_name": "República Checa", "code": "420" },
    { "id": 192, "country_name": "República Dominicana", "code": "1 809" },
    { "id": 194, "country_name": "Ruanda", "code": "250" },
    { "id": 195, "country_name": "Rumanía", "code": "40" },
    { "id": 196, "country_name": "Rusia", "code": "7" },
    { "id": 198, "country_name": "Samoa", "code": "685" },
    { "id": 199, "country_name": "Samoa Americana", "code": "1 684" },
    { "id": 200, "country_name": "San Bartolomé", "code": "590" },
    { "id": 201, "country_name": "San Cristóbal y Nieves", "code": "1 869" },
    { "id": 202, "country_name": "San Marino", "code": "378" },
    { "id": 203, "country_name": "San Martín (Francia)", "code": "1 599" },
    { "id": 204, "country_name": "San Pedro y Miquelón", "code": "508" },
    { "id": 205, "country_name": "San Vicente y las Granadinas", "code": "1 784" },
    { "id": 206, "country_name": "Santa Elena", "code": "290" },
    { "id": 207, "country_name": "Santa Lucía", "code": "1 758" },
    { "id": 208, "country_name": "Santo Tomé y Príncipe", "code": "239" },
    { "id": 209, "country_name": "Senegal", "code": "221" },
    { "id": 210, "country_name": "Serbia", "code": "381" },
    { "id": 211, "country_name": "Seychelles", "code": "248" },
    { "id": 212, "country_name": "Sierra Leona", "code": "232" },
    { "id": 213, "country_name": "Singapur", "code": "65" },
    { "id": 214, "country_name": "Siria", "code": "963" },
    { "id": 215, "country_name": "Somalia", "code": "252" },
    { "id": 216, "country_name": "Sri lanka", "code": "94" },
    { "id": 217, "country_name": "Sudáfrica", "code": "27" },
    { "id": 218, "country_name": "Sudán", "code": "249" },
    { "id": 219, "country_name": "Suecia", "code": "46" },
    { "id": 220, "country_name": "Suiza", "code": "41" },
    { "id": 221, "country_name": "Surinám", "code": "597" },
    { "id": 223, "country_name": "Swazilandia", "code": "268" },
    { "id": 224, "country_name": "Tadjikistán", "code": "992" },
    { "id": 225, "country_name": "Tailandia", "code": "66" },
    { "id": 226, "country_name": "Taiwán", "code": "886" },
    { "id": 227, "country_name": "Tanzania", "code": "255" },
    { "id": 230, "country_name": "Timor Oriental", "code": "670" },
    { "id": 231, "country_name": "Togo", "code": "228" },
    { "id": 232, "country_name": "Tokelau", "code": "690" },
    { "id": 233, "country_name": "Tonga", "code": "676" },
    { "id": 234, "country_name": "Trinidad y Tobago", "code": "1 868" },
    { "id": 235, "country_name": "Tunez", "code": "216" },
    { "id": 236, "country_name": "Turkmenistán", "code": "993" },
    { "id": 237, "country_name": "Turquía", "code": "90" },
    { "id": 238, "country_name": "Tuvalu", "code": "688" },
    { "id": 239, "country_name": "Ucrania", "code": "380" },
    { "id": 240, "country_name": "Uganda", "code": "256" },
    { "id": 241, "country_name": "Uruguay", "code": "598" },
    { "id": 242, "country_name": "Uzbekistán", "code": "998" },
    { "id": 243, "country_name": "Vanuatu", "code": "678" },
    { "id": 244, "country_name": "Venezuela", "code": "58" },
    { "id": 245, "country_name": "Vietnam", "code": "84" },
    { "id": 246, "country_name": "Wallis y Futuna", "code": "681" },
    { "id": 247, "country_name": "Yemen", "code": "967" },
    { "id": 248, "country_name": "Yibuti", "code": "253" },
    { "id": 249, "country_name": "Zambia", "code": "260" },
    { "id": 250, "country_name": "Zimbabue", "code": "263" }
]
