module.exports = [
    { id: 1, name: 'Ciudad Autonoma de Buenos Aires', value: 'CABA'},
    { id: 2, name: 'Buenos Aires', value: 'Buenos Aires' },
    { id: 3, name: 'Catamarca', value: 'Catamarca'},
    { id: 4, name: 'Chaco', value: 'Chaco'},
    { id: 5, name: 'Chubut', value: 'Chubut'},
    { id: 6, name: 'Córdoba', value: 'Córdoba'},
    { id: 7, name: 'Corrientes', value: 'Corrientes'},
    { id: 8, name: 'Entre Ríos', value: 'Entre Ríos'},
    { id: 9, name: 'Formosa', value: 'Formosa'},
    { id: 10, name: 'Jujuy', value: 'Jujuy'},
    { id: 11, name: 'La Pampa', value: 'La Pampa'},
    { id: 12, name: 'La Rioja', value: 'La Rioja'},
    { id: 13, name: 'Mendoza', value: 'Mendoza'},
    { id: 14, name: 'Misiones', value: 'Misiones'},
    { id: 15, name: 'Neuquén', value: 'Neuquén'},
    { id: 16, name: 'Río Negro', value: 'Río Negro'},
    { id: 17, name: 'Salta', value: 'Salta'},
    { id: 18, name: 'San Juan', value: 'San Juan'},
    { id: 19, name: 'San Luis', value: 'San Luis'},
    { id: 20, name: 'Santa Cruz', value: 'Santa Cruz'},
    { id: 21, name: 'Santa Fe', value: 'Santa Fe'},
    { id: 22, name: 'Santiago del Estero', value: 'Santiago del Estero'},
    { id: 23, name: 'Tierra del Fuego', value: 'Tierra del Fuego'},
    { id: 24, name: 'Tucumán', value: 'Tucumán'}
]