module.exports = [
    { id: 1, name: 'Ciudad Autonoma de Buenos Aires', value: 'Ciudad Autonoma de Buenos Aires', CSCode: 'C'},
    { id: 2, name: 'Buenos Aires', value: 'Buenos Aires' , CSCode: 'B'},
    { id: 3, name: 'Catamarca', value: 'Catamarca', CSCode: 'K'},
    { id: 4, name: 'Chaco', value: 'Chaco', CSCode: 'H'},
    { id: 5, name: 'Chubut', value: 'Chubut', CSCode: 'U'},
    { id: 6, name: 'Córdoba', value: 'Córdoba', CSCode: 'X'},
    { id: 7, name: 'Corrientes', value: 'Corrientes', CSCode: ''},
    { id: 8, name: 'Entre Ríos', value: 'Entre Ríos', CSCode: 'E'},
    { id: 9, name: 'Formosa', value: 'Formosa', CSCode: 'P'},
    { id: 10, name: 'Jujuy', value: 'Jujuy', CSCode: 'Y'},
    { id: 11, name: 'La Pampa', value: 'La Pampa', CSCode: 'L'},
    { id: 12, name: 'La Rioja', value: 'La Rioja', CSCode: 'F'},
    { id: 13, name: 'Mendoza', value: 'Mendoza', CSCode: 'M'},
    { id: 14, name: 'Misiones', value: 'Misiones', CSCode: 'N'},
    { id: 15, name: 'Neuquén', value: 'Neuquén', CSCode: 'Q'},
    { id: 16, name: 'Río Negro', value: 'Río Negro', CSCode: 'R'},
    { id: 17, name: 'Salta', value: 'Salta', CSCode: 'A'},
    { id: 18, name: 'San Juan', value: 'San Juan', CSCode: 'J'},
    { id: 19, name: 'San Luis', value: 'San Luis', CSCode: 'D'},
    { id: 20, name: 'Santa Cruz', value: 'Santa Cruz', CSCode: 'Z'},
    { id: 21, name: 'Santa Fe', value: 'Santa Fe', CSCode: 'S'},
    { id: 22, name: 'Santiago del Estero', value: 'Santiago del Estero', CSCode: 'G'},
    { id: 23, name: 'Tierra del Fuego', value: 'Tierra del Fuego', CSCode: 'V'},
    { id: 24, name: 'Tucumán', value: 'Tucumán', CSCode: 'T'}
]